spring:
  datasource:
    url: jdbc:mysql://47.105.194.138:3306/Bank
    username: root
    password: 655424wxsywsh
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 50
    maxActive: 200
    maxWait: 60000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    #Target database
    database: mysql
    #控制台显示SQL
    show-sql: true
    #Whether to initialize the schema on startup，可不配
    generate-ddl: false
    #    # mappingResources用于指定和实体相关的的hibernate配置文件 可不配，通常在实体上面使用注解
    #    mappingResources:
    #      - classpath: /hibernate/User.hbm.xml
    #      - classpath: /hibernate/Address.hbm.xml
    # Register OpenEntityManagerInViewInterceptor 默认为true
    open-in-view: true
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



